config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :factura_elementos

  resources :facturas

  resources :numero_facturas

  resources :guia_elementos

  resources :guias

  resources :destinatarios

  resources :remitente_direcciones

  resources :remitentes

  resources :placas

  resources :numero_guias

  resources :distritos

  resources :provincias

  resources :departamentos

   root 'guias#index'

end

app/models/departamento.rb
class Departamento < ActiveRecord::Base
	has_many :provincias
end

app/models/destinatario.rb
class Destinatario < ActiveRecord::Base
end

app/models/distrito.rb
class Distrito < ActiveRecord::Base
	belongs_to :provincia	
end

app/models/factura.rb
class Factura < ActiveRecord::Base
end

app/models/factura_elemento.rb
class FacturaElemento < ActiveRecord::Base
end

app/models/guia.rb
class Guia < ActiveRecord::Base
	belongs_to :partida_distrito, :class_name => 'Distrito', :foreign_key => 'partida_distrito_id'
	belongs_to :llegada_distrito, :class_name => 'Distrito', :foreign_key => 'llegada_distrito_id'
end

app/models/guia_elemento.rb
class GuiaElemento < ActiveRecord::Base
end

app/models/numero_factura.rb
class NumeroFactura < ActiveRecord::Base
end

app/models/numero_guia.rb
class NumeroGuia < ActiveRecord::Base
end

app/models/placa.rb
class Placa < ActiveRecord::Base
end

app/models/provincia.rb
class Provincia < ActiveRecord::Base
	belongs_to :departamento
	has_many :distritos
	accepts_nested_attributes_for :distritos, :reject_if => :all_blank, :allow_destroy => true
end

app/models/remitente.rb
class Remitente < ActiveRecord::Base
	has_many :remitente_direcciones
	accepts_nested_attributes_for :remitente_direcciones, :reject_if => :all_blank, :allow_destroy => true
end

app/models/remitente_direccione.rb
class RemitenteDireccione < ActiveRecord::Base
	belongs_to :remitente
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/remitentes_controller.rb
class RemitentesController < InheritedResources::Base
	def permitted_params
		params.permit!
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/distritos_helper.rb
module DistritosHelper
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/helpers/guias_helper.rb
module GuiasHelper
end

app/helpers/numero_guias_helper.rb
module NumeroGuiasHelper
end

app/helpers/placas_helper.rb
module PlacasHelper
end

app/helpers/provincias_helper.rb
module ProvinciasHelper
end

app/helpers/remitentes_helper.rb
module RemitentesHelper
end

app/views/remitentes/_form.html.haml
= form_for @remitente, :html => { class: 'form-horizontal', role: 'form' } do |f|
  - if @remitente.errors.any?
    #error_explanation
      %h2= "#{pluralize(@remitente.errors.count, "error")}"
      %ul
        - @remitente.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :nombre_razon, class: 'col-sm-2 control-label'
    .col-sm-3
      = f.text_field :nombre_razon, class: 'form-control'
  .form-group
    = f.label :ruc, class: 'col-sm-2 control-label'
    .col-sm-3
      = f.text_field :ruc, class: 'form-control'
  .form-group
    = f.label :dni, class: 'col-sm-2 control-label'
    .col-sm-2
      = f.text_field :dni, class: 'form-control'

  %h3 Direcciones  
  %br
  = f.fields_for :remitente_direcciones do |remitente_direccione|
    = render 'remitente_direccione_fields', :f => remitente_direccione  
  #distritos
    = link_to_add_association 'add Direccion', f, :remitente_direcciones, class: 'btn btn-default'
  %br
  .actions
    = f.submit 'Guardar', class: 'btn btn-default'
    - if params[:action] == 'edit'
      = link_to 'Ver', @remitente, class: 'btn btn-info'
    = link_to 'Regresar', 'javascript:history.back(-1)', class: 'btn btn-warning'

app/views/remitentes/_remitente_direccione_fields.html.haml
.form-group.nested-fields
  .col-sm-4
    = f.text_field :direccion, class: 'form-control'
  .col-sm-1
    = link_to_remove_association "borrar", f, class: 'btn btn-default'

app/views/remitentes/edit.html.haml
- page_title!('Editando remitente')

#region-remitentes.container

  .region
    .region-title
      %h1
        Editando
        %b
          remitente

  .region
    = render 'form'

app/views/remitentes/index.html.haml
.page-header
  %h1 
    Principal
    %b Remitentes

= link_to 'Crear Remitente', new_remitente_path, class: 'btn btn-primary'
%br
%br
.table-responsive
  %table.table
    %tr
      %th Nombre razon
      %th Ruc
      %th Dni
      %th Acciones
      
      

    - @remitentes.each do |remitente|
      %tr
        %td= remitente.nombre_razon
        %td= remitente.ruc
        %td= remitente.dni
        %td
          = link_to 'Ver', remitente, class: 'btn btn-info'      
          = link_to 'Editar', edit_remitente_path(remitente), class: 'btn btn-success'
          = link_to 'Eliminar', remitente, :method => :delete, :data => { :confirm => '¿Estás Seguro?' }, class: 'btn btn-danger'

app/views/remitentes/new.html.haml
- page_title!('Creando remitente')

#region-remitentes.container

  .region
    .region-title
      %h1
        Creando
        %b
          remitente

  .region
    = render 'form'

app/views/remitentes/show.html.haml
.page-header
  %h1 Remitente

%p
  %b Nombre razon:
  = @remitente.nombre_razon
%p
  %b Ruc:
  = @remitente.ruc
%p
  %b Dni:
  = @remitente.dni

%h3 Direcciones

- @remitente.remitente_direcciones.each do |remitente_direccione|
  = remitente_direccione.direccion
  %br
%br
= link_to 'Editar', edit_remitente_path(@remitente), class: 'btn btn-success'
= link_to 'Regresar', remitentes_path, class: 'btn btn-warning'