config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :factura_elementos

  resources :facturas

  resources :numero_facturas

  resources :guia_elementos

  resources :guias

  resources :destinatarios

  resources :remitente_direcciones

  resources :remitentes

  resources :placas

  resources :numero_guias

  resources :distritos

  resources :provincias

  resources :departamentos

   root 'guias#index'

end

app/models/departamento.rb
class Departamento < ActiveRecord::Base
	has_many :provincias
end

app/models/destinatario.rb
class Destinatario < ActiveRecord::Base
end

app/models/distrito.rb
class Distrito < ActiveRecord::Base
	belongs_to :provincia	
end

app/models/factura.rb
class Factura < ActiveRecord::Base
end

app/models/factura_elemento.rb
class FacturaElemento < ActiveRecord::Base
end

app/models/guia.rb
class Guia < ActiveRecord::Base
	belongs_to :partida_distrito, :class_name => 'Distrito', :foreign_key => 'partida_distrito_id'
	belongs_to :llegada_distrito, :class_name => 'Distrito', :foreign_key => 'llegada_distrito_id'
end

app/models/guia_elemento.rb
class GuiaElemento < ActiveRecord::Base
end

app/models/numero_factura.rb
class NumeroFactura < ActiveRecord::Base
end

app/models/numero_guia.rb
class NumeroGuia < ActiveRecord::Base
end

app/models/placa.rb
class Placa < ActiveRecord::Base
end

app/models/provincia.rb
class Provincia < ActiveRecord::Base
	belongs_to :departamento
	has_many :distritos
	accepts_nested_attributes_for :distritos, :reject_if => :all_blank, :allow_destroy => true
end

app/models/remitente.rb
class Remitente < ActiveRecord::Base
	has_many :remitente_direcciones
	accepts_nested_attributes_for :remitente_direcciones, :reject_if => :all_blank, :allow_destroy => true
end

app/models/remitente_direccione.rb
class RemitenteDireccione < ActiveRecord::Base
	belongs_to :remitente
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/provincias_controller.rb
class ProvinciasController < InheritedResources::Base
	def permitted_params
		params.permit!
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/distritos_helper.rb
module DistritosHelper
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/helpers/guias_helper.rb
module GuiasHelper
end

app/helpers/numero_guias_helper.rb
module NumeroGuiasHelper
end

app/helpers/placas_helper.rb
module PlacasHelper
end

app/helpers/provincias_helper.rb
module ProvinciasHelper
end

app/helpers/remitentes_helper.rb
module RemitentesHelper
end

app/views/provincias/_distrito_fields.html.haml
.form-group.nested-fields
  .col-sm-4
    = f.text_field :nombre, class: 'form-control'
  .col-sm-2
    = link_to_remove_association "Borrar", f, class: 'btn btn-default'

app/views/provincias/_form.html.haml
= form_for @provincia, :html => { class: 'form-horizontal', role: 'form' } do |f|
  - if @provincia.errors.any?
    #error_explanation
      %h2= "#{pluralize(@provincia.errors.count, "error")}"
      %ul
        - @provincia.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :departamento_id, class: 'col-sm-2 control-label'
    .col-sm-3
      = f.select :departamento_id, Departamento.all.collect{|x| [x.nombre, x.id]},class: 'form-control'
  .form-group
    = f.label :provincia, class: 'col-sm-2 control-label'
    .col-sm-2
      = f.text_field :nombre, class: 'form-control'



  %h3 Distritos
  /%hr{:style => 'border-color: #ccc;'}
  %br
  = f.fields_for :distritos do |distrito|
    = render 'distrito_fields', :f => distrito  
  #distritos
    = link_to_add_association 'add distrito', f, :distritos, class: 'btn btn-default'
  %br
  .form-group    
    = f.submit 'Guardar', class: 'btn btn-primary'
    = link_to 'Regresar', 'javascript:history.back(-1)', class: 'btn btn-warning'

app/views/provincias/edit.html.haml
- page_title!('Editando provincia')

#region-provincias.container

  .region
    .region-title
      %h1
        Editando
        %b
          provincia

  .region
    = render 'form'

  .region
    .admin-controls
      = link_to 'Ver', @provincia, class: 'btn btn-info'
      = link_to 'Regresar', 'javascript:history.back(-1)', class: 'btn btn-warning'

app/views/provincias/index.html.haml
.page-header
  %h1 
    Provincias
.row
  .col-sm-8
    = link_to 'Crear Provincia', new_provincia_path, class: 'btn btn-primary'
    %br
    %br
    .table-responsive
      %table.table
        %tr
          %th Nombre
          %th Departamento
          %th Acciones          

        - @provincias.each do |provincia|
          %tr
            %td= provincia.nombre
            %td= provincia.departamento_id
            %td
              = link_to 'Ver', provincia, class: 'btn btn-info'            
              = link_to 'Editar', edit_provincia_path(provincia), class: 'btn btn-success'
              = link_to 'Eliminar', provincia, :method => :delete, :data => { :confirm => '¿Estás Seguro?' }, class: 'btn btn-danger'

app/views/provincias/new.html.haml
- page_title!('Creando provincia')

#region-provincias.container

  .region
    .region-title
      %h1
        Creando
        %b
          provincia

  .region
    = render 'form'

  
  
      

app/views/provincias/show.html.haml
#region-provincias.container
  .region
    .region-title
      %h1= page_title!('provincia')

  .region
    %p
      %b Nombre:
      = @provincia.nombre
    %p
      %b Departamento:
      = @provincia.departamento_id

  
.admin-controls
  = link_to 'Editar', edit_provincia_path(@provincia), class: 'btn btn-success'
  = link_to 'Regresar', provincias_path, class: 'btn btn-warning'