config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :factura_elementos

  resources :facturas

  resources :numero_facturas

  resources :guia_elementos

  resources :guias

  resources :destinatarios

  resources :remitente_direcciones

  resources :remitentes

  resources :placas

  resources :numero_guias

  resources :distritos

  resources :provincias

  resources :departamentos

   root 'guias#index'

end

app/models/departamento.rb
class Departamento < ActiveRecord::Base
	has_many :provincias
end

app/models/destinatario.rb
class Destinatario < ActiveRecord::Base
end

app/models/distrito.rb
class Distrito < ActiveRecord::Base
	belongs_to :provincia	
end

app/models/factura.rb
class Factura < ActiveRecord::Base
end

app/models/factura_elemento.rb
class FacturaElemento < ActiveRecord::Base
end

app/models/guia.rb
class Guia < ActiveRecord::Base
	belongs_to :partida_distrito, :class_name => 'Distrito', :foreign_key => 'partida_distrito_id'
	belongs_to :llegada_distrito, :class_name => 'Distrito', :foreign_key => 'llegada_distrito_id'
end

app/models/guia_elemento.rb
class GuiaElemento < ActiveRecord::Base
end

app/models/numero_factura.rb
class NumeroFactura < ActiveRecord::Base
end

app/models/numero_guia.rb
class NumeroGuia < ActiveRecord::Base
end

app/models/placa.rb
class Placa < ActiveRecord::Base
end

app/models/provincia.rb
class Provincia < ActiveRecord::Base
	belongs_to :departamento
	has_many :distritos
	accepts_nested_attributes_for :distritos, :reject_if => :all_blank, :allow_destroy => true
end

app/models/remitente.rb
class Remitente < ActiveRecord::Base
	has_many :remitente_direcciones
	accepts_nested_attributes_for :remitente_direcciones, :reject_if => :all_blank, :allow_destroy => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/factura_elementos_controller.rb
class FacturaElementosController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/distritos_helper.rb
module DistritosHelper
end

app/helpers/factura_elementos_helper.rb
module FacturaElementosHelper
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/helpers/guias_helper.rb
module GuiasHelper
end

app/helpers/numero_guias_helper.rb
module NumeroGuiasHelper
end

app/helpers/placas_helper.rb
module PlacasHelper
end

app/helpers/provincias_helper.rb
module ProvinciasHelper
end

app/helpers/remitentes_helper.rb
module RemitentesHelper
end

app/views/factura_elementos/_form.html.haml
= form_for @factura_elemento, :html => { class: 'form-horizontal', role: 'form' } do |f|
  - if @factura_elemento.errors.any?
    #error_explanation
      %h2= "#{pluralize(@factura_elemento.errors.count, "error")}"
      %ul
        - @factura_elemento.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :primera_guia_id, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :primera_guia_id, class: 'form-control'
  .form-group
    = f.label :segunda_guia_id, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :segunda_guia_id, class: 'form-control'
  .form-group
    = f.label :factura_id, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :factura_id, class: 'form-control'
  .form-group
    = f.label :precio, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :precio, class: 'form-control'
  .actions
    = f.submit 'Guardar', class: 'btn btn-default'

app/views/factura_elementos/edit.html.haml
- page_title!('Editando factura_elemento')

#region-factura_elementos.container

  .region
    .region-title
      %h1
        Editando
        %b
          factura_elemento

  .region
    = render 'form'

  .region
    .admin-controls
      = link_to 'Ver', @factura_elemento, class: 'btn btn-info'
      = link_to 'Regresar', 'javascript:history.back(-1)', class: 'btn btn-warning'

app/views/factura_elementos/index.html.haml
#region-factura_elementos.container

  .region
    .region-title
      %h1= page_title!('factura_elementos')

    .region
      - if current_admin
        .admin-control
          = link_to 'Crear Factura elemento', new_factura_elemento_path, class: 'btn btn-primary'

      .table-responsive
        %table.table
          %tr
            %th Primera guia
            %th Segunda guia
            %th Factura
            %th Precio
            %th
            %th
            %th

          - @factura_elementos.each do |factura_elemento|
            %tr
              %td= factura_elemento.primera_guia_id
              %td= factura_elemento.segunda_guia_id
              %td= factura_elemento.factura_id
              %td= factura_elemento.precio
              %td= link_to 'Ver', factura_elemento, class: 'btn btn-info'
              - if current_admin
                %td= link_to 'Editar', edit_factura_elemento_path(factura_elemento), class: 'btn btn-success'
                %td= link_to 'Eliminar', factura_elemento, :method => :delete, :data => { :confirm => '¿Estás Seguro?' }, class: 'btn btn-danger'

app/views/factura_elementos/new.html.haml
- page_title!('Creando factura_elemento')

#region-factura_elementos.container

  .region
    .region-title
      %h1
        Creando
        %b
          factura_elemento

  .region
    = render 'form'

  .region
    .admin-controls
      = link_to 'Regresar', 'javascript:history.back(-1)', class: 'btn btn-warning'

app/views/factura_elementos/show.html.haml
#region-factura_elementos.container
  .region
    .region-title
      %h1= page_title!('factura_elemento')

  .region
    %p
      %b Primera guia:
      = @factura_elemento.primera_guia_id
    %p
      %b Segunda guia:
      = @factura_elemento.segunda_guia_id
    %p
      %b Factura:
      = @factura_elemento.factura_id
    %p
      %b Precio:
      = @factura_elemento.precio

  .region
    - if current_admin
      .admin-controls
        = link_to 'Editar', edit_factura_elemento_path(@factura_elemento), class: 'btn btn-success'
    = link_to 'Regresar', factura_elementos_path, class: 'btn btn-warning'